### ISSUE TITLE
Migrate project from CRA(Create-React-App) to Vite.

### ISSUE THREAD

**Issue by albeniskerqeli10** [albeniskerqeli10/Reactjs-Ecommerce-App#7]

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by GIT-Gizmo** [comment]
Hi, I am willing to help on this if the issue is still looking to be fixed

**Comment by albeniskerqeli10** [comment]
Closing this issue because of PR #8

**Comment by albeniskerqeli10** [comment]
Closing this issue because of PR #8
